#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# FreshScan AI — Local Dev Setup Script
# Run once after cloning: sh scripts/dev-setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND="$REPO_ROOT/backend"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log()  { echo -e "${CYAN}[setup]${RESET} $1"; }
ok()   { echo -e "${GREEN}  [OK]${RESET} $1"; }
warn() { echo -e "${YELLOW}  [WARN]${RESET}  $1"; }

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}   FreshScan AI — Local Dev Setup${RESET}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

# ── Step 1: Frontend deps ─────────────────────────────────────────────────────
log "Installing frontend dependencies..."
cd "$REPO_ROOT"
npm install
ok "node_modules ready"

# ── Step 2: Frontend env ──────────────────────────────────────────────────────
if [ ! -f "$REPO_ROOT/.env.local" ]; then
  log "Creating .env.local (enables Dev Login button)..."
  echo "VITE_DEV_MODE=true" > "$REPO_ROOT/.env.local"
  ok ".env.local created"
else
  ok ".env.local already exists"
fi

# ── Step 3: Python venv ───────────────────────────────────────────────────────
log "Creating Python virtual environment..."
if [ ! -d "$REPO_ROOT/.venv" ]; then
  python3 -m venv "$REPO_ROOT/.venv"
  ok ".venv created"
else
  ok ".venv already exists"
fi

log "Installing Python dependencies..."
"$REPO_ROOT/.venv/bin/pip" install --quiet --upgrade pip
"$REPO_ROOT/.venv/bin/pip" install --quiet -r "$BACKEND/requirements.txt"
ok "Python packages installed"

# ── Step 4: Check for Supabase CLI + Docker ────────────────────────────────────
USE_LOCAL_SUPABASE=false

if ! command -v supabase &>/dev/null; then
  warn "Supabase CLI not found. Skipping local DB setup."
  warn "Install it with: brew install supabase/tap/supabase"
  warn "Then re-run this script to get a fully local database."
elif ! docker info &>/dev/null 2>&1; then
  warn "Docker is not running. Skipping local DB setup."
  warn "Start Docker Desktop, then re-run this script."
else
  USE_LOCAL_SUPABASE=true
fi

if [ "$USE_LOCAL_SUPABASE" = true ]; then
  log "Starting local Supabase (Docker)..."
  cd "$BACKEND"
  supabase start 2>&1 | tail -20

  log "Applying migrations and seed data..."
  supabase db reset --no-verify-jwt 2>&1 | tail -5
  ok "Local Supabase ready"

  # Extract the local credentials from supabase status
  LOCAL_URL=$(supabase status 2>/dev/null | grep "API URL" | awk '{print $NF}')
  LOCAL_ANON=$(supabase status 2>/dev/null | grep "anon key" | awk '{print $NF}')

  if [ -n "$LOCAL_URL" ] && [ -n "$LOCAL_ANON" ]; then
    log "Writing local Supabase credentials to backend/.env..."
    cat > "$BACKEND/.env" <<EOF
# ── Auto-generated by dev-setup.sh ────────────────────────────────────────────
# Local Supabase (Docker) — completely isolated from production.
SUPABASE_URL=$LOCAL_URL
SUPABASE_KEY=$LOCAL_ANON
SUPABASE_SERVICE_KEY=
FRONTEND_URL=http://localhost:5173
API_BASE_URL=http://localhost:8000
CORS_ALLOW_ALL=true
DEV_BYPASS_AUTH=true
DEV_BYPASS_TOKEN=dev-local-bypass-token
EOF
    ok "backend/.env written with local Supabase credentials"
  else
    warn "Could not extract local Supabase credentials automatically."
    warn "Run 'cd backend && supabase status' and copy API URL + anon key to backend/.env"
  fi
else
  # Fallback — use the shared dev Supabase (anon key from .env.example)
  if [ ! -f "$BACKEND/.env" ]; then
    log "Copying backend/.env.example → backend/.env (shared dev Supabase)..."
    cp "$BACKEND/.env.example" "$BACKEND/.env"
    ok "backend/.env ready (uses shared dev Supabase — safe, isolated by user_id)"
  else
    ok "backend/.env already exists"
  fi
fi

# ── Done ───────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}${BOLD}  [OK] Setup complete!${RESET}"
echo ""
echo -e "  Run:  ${BOLD}npm run dev${RESET}"
echo -e "  Open: ${BOLD}http://localhost:5173${RESET}"
echo -e "  Auth: Click ${BOLD}DEV LOGIN${RESET} — no Google account needed"
if [ "$USE_LOCAL_SUPABASE" = true ]; then
  echo -e "  DB:   Local Docker — ${BOLD}fully isolated from production${RESET}"
else
  echo -e "  DB:   Shared dev Supabase — ${BOLD}isolated by user_id${RESET}"
  echo ""
  echo -e "  ${YELLOW}For a fully local DB:${RESET}"
  echo -e "    brew install supabase/tap/supabase  # install CLI"
  echo -e "    open Docker Desktop                 # start Docker"
  echo -e "    sh scripts/dev-setup.sh             # re-run this script"
fi
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
